"""add constraint to bookings time

Revision ID: afefd2e66366
Revises: 001b642dd68b
Create Date: 2026-08-20 20:41:00.417832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afefd2e66366'
down_revision: Union[str, Sequence[str], None] = '001b642dd68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")

    op.execute("""
            ALTER TABLE bookings
            ADD CONSTRAINT booking_no_overlap
            EXCLUDE USING gist (
                room_id WITH =,
                tstzrange(start, "end", '[)') WITH &&
            )
            WHERE (status IN ('hold', 'confirmed'));
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE bookings DROP CONSTRAINT booking_no_overlap;")
    # ### end Alembic commands ###
