from typing import Protocol

from booking.domain.refresh_token.models import RefreshToken


class TokenRepository(Protocol):
    async def add(self, token: RefreshToken) -> RefreshToken: ...
    async def get_by_hash(self, token_hash: str) -> RefreshToken | None: ...
    async def revoke(self, token: RefreshToken) -> None: ...
    async def revoke_all(self, user_id: int) -> None: ...
